In [2]:
import numpy as np

In [7]:
def svd_approximation(A, k):
    """
    Approximates matrix A using the top k singular values via SVD.
    
    Parameters:
        A (np.ndarray): Input matrix (m x n)
        k (int): Number of singular values to retain (1 <= k <= min(m, n))
    
    Returns:
        A_approx (np.ndarray): Rank-k approximation of A (m x n)
    """
    # Perform SVD
    U, s, Vt = np.linalg.svd(A, full_matrices=False)
    
    # top k singular values
    U_k = U[:, :k]          # (m, k)
    s_k = s[:k]             # (k, )
    Vt_k = Vt[:k, :]        # (k, n)
    
    # Reconstruct the rank-k approximation
    Sigma_k = np.diag(s_k)  # Diagonal matrix of top k singular values (k x k)
    A_approx = U_k @ Sigma_k @ Vt_k
    
    return A_approx

In [8]:
# Test with a sample matrix from book page 93

A = np.array([[0.96, 1.72], [2.28, 0.96]])

# Compute rank-1 approximation
A_rank1 = svd_approximation(A, k=1)

# Compute rank-2 approximation (exact since original matrix is rank 2)
A_rank2 = svd_approximation(A, k=2)

print("Original Matrix:")
print(A)
print("\nRank-1 Approximation:")
print(A_rank1)
print("\nRank-2 Approximation (Exact Reconstruction):")
print(A_rank2)

Original Matrix:
[[0.96 1.72]
 [2.28 0.96]]

Rank-1 Approximation:
[[1.44 1.08]
 [1.92 1.44]]

Rank-2 Approximation (Exact Reconstruction):
[[0.96 1.72]
 [2.28 0.96]]
