In [5]:
import numpy as np

In [3]:
def classical_gram_schmidt(A):
    """
    Classical Gram-Schmidt process for QR decomposition.
    
    Parameters:
        A (np.array): Input matrix.
    
    Returns:
        tuple: Q (orthogonal matrix), R (upper triangular matrix)
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R

In [6]:
#An example from the note p 82
A = np.array([[2, 4, -4],
              [1, 5, -5],
              [2, 10, 5]], dtype=float)

Q, R = classical_gram_schmidt(A)

print("Matrix Q (Orthogonal):")
print(Q)
print("\nMatrix R (Upper Triangular):")
print(R)

Matrix Q (Orthogonal):
[[ 6.66666667e-01 -7.45355992e-01 -6.62009108e-17]
 [ 3.33333333e-01  2.98142397e-01 -8.94427191e-01]
 [ 6.66666667e-01  5.96284794e-01  4.47213595e-01]]

Matrix R (Upper Triangular):
[[ 3.         11.         -1.        ]
 [ 0.          4.47213595  4.47213595]
 [ 0.          0.          6.70820393]]


In [7]:
Q@R

array([[ 2.,  4., -4.],
       [ 1.,  5., -5.],
       [ 2., 10.,  5.]])