In [1]:
import numpy as np

در الگوريتم گرام اشميت بردار  کا ام به گونه اي ساخته مي شود كه در يك گام بر کا منهای یک بردار قبلی عمود باشد که در این صورت تولید خطا میکند.
اما در گرام اشمیت اصلاح شده بردار کا ام به گونه ای ساخته میشود که در یک گام بر بردار اول و در گام دیگر بر بردار دوم و همینطور الی آخر.
به این ترتیب خطا کمتر خواهد بود.

In [2]:
def modified_gram_schmidt(A):
    """
    Modified Gram-Schmidt process for QR decomposition.
    
    Parameters:
        A (np.array): Input matrix.
    
    Returns:
        tuple: Q (orthogonal matrix), R (upper triangular matrix)
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for i in range(n):
        R[i, i] = np.linalg.norm(A[:, i])
        Q[:, i] = A[:, i] / R[i, i]
        for j in range(i + 1, n):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            A[:, j] -= R[i, j] * Q[:, i]
    return Q, R

In [3]:
A = np.array([[2, 4, -4],
              [1, 5, -5],
              [2, 10, 5]], dtype=float)

Q, R = modified_gram_schmidt(A)

print("Matrix Q (Orthogonal):")
print(Q)
print("\nMatrix R (Upper Triangular):")
print(R)

Matrix Q (Orthogonal):
[[ 6.66666667e-01 -7.45355992e-01 -6.62009108e-17]
 [ 3.33333333e-01  2.98142397e-01 -8.94427191e-01]
 [ 6.66666667e-01  5.96284794e-01  4.47213595e-01]]

Matrix R (Upper Triangular):
[[ 3.         11.         -1.        ]
 [ 0.          4.47213595  4.47213595]
 [ 0.          0.          6.70820393]]


In [4]:
Q@R

array([[ 2.,  4., -4.],
       [ 1.,  5., -5.],
       [ 2., 10.,  5.]])