In [16]:
import numpy as np

In [17]:
def svd_decomposition(A):
    """
    Perform Singular Value Decomposition (SVD) of a matrix A.
    
    Parameters:
        A (np.ndarray): Input matrix (m x n).
    
    Returns:
        U (np.ndarray): Left singular vectors (m x m).
        Sigma (np.ndarray): Singular values (m x n).
        Vt (np.ndarray): Right singular vectors (n x n), transposed.
    """
    # Step 1: Compute A^T * A and A * A^T
    AtA = np.dot(np.transpose(A), A)
    AAt = np.dot(A, np.transpose(A))
    
    # Step 2: Compute eigenvalues and eigenvectors
    eigenvalues_AtA, V = np.linalg.eigh(AtA)
    eigenvalues_AAt, U = np.linalg.eigh(AAt)
    
    # Step 3: Sort eigenvalues and eigenvectors in descending order
    idx = np.argsort(eigenvalues_AtA)[::-1]
    eigenvalues_AtA = eigenvalues_AtA[idx]
    V = V[:, idx]
    
    idx = np.argsort(eigenvalues_AAt)[::-1]
    eigenvalues_AAt = eigenvalues_AAt[idx]
    U = U[:, idx]
    
    # Step 4: Compute singular values (square roots of eigenvalues)
    singular_values = np.sqrt(np.maximum(eigenvalues_AtA, 0))
    
    # Step 5: Construct Sigma matrix
    Sigma = np.zeros_like(A)
    for i in range(min(A.shape)):
        Sigma[i, i] = singular_values[i]
    
    # Step 6: Ensure correct signs of U and V
    for i in range(len(singular_values)):
        if np.dot(A @ V[:, i], U[:, i]) < 0:
            U[:, i] = -U[:, i]
    
    return U, Sigma, np.transpose(V)


In [18]:
# Test with a sample matrix from book page 93
A = np.array([[0.96, 1.72], [2.28, 0.96]])
U, Sigma, Vt = svd_decomposition(A)

In [19]:
# Output the matrices
print("U Matrix:\n", U)
print("Sigma Matrix:\n", Sigma)
print("V Transpose Matrix:\n", Vt)

U Matrix:
 [[-0.6 -0.8]
 [-0.8  0.6]]
Sigma Matrix:
 [[3. 0.]
 [0. 1.]]
V Transpose Matrix:
 [[-0.8 -0.6]
 [ 0.6 -0.8]]


In [20]:
# Verify reconstruction
reconstructed_A = (U @ Sigma) @ Vt
print("Reconstructed Matrix A:\n", reconstructed_A)

Reconstructed Matrix A:
 [[0.96 1.72]
 [2.28 0.96]]
